on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Create executable for Mac
        if: matrix.os == 'macos-latest'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pyinstaller --onefile main.py

      - name: Create executable for Windows
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pyinstaller --onefile main.py

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Publish for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            include:
              - os: windows-latest
                artifact_name: main.exe
                asset_name: main.exe
              - os: macos-latest
                artifact_name: main
                asset_name: main
        steps:
          - name: Upload binaries to release
            uses: svenstaro/upload-release-action@v2
            with:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
              file: ./dist/${{ matrix.artifact_name }}
              asset_name: ${{ matrix.asset_name }}
              tag: ${{ github.ref }}
